services:
  app:
    build: .
    container_name: php_api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - api_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_database
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network

#  angular:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: angular_frontend
#    ports:
#      - "4200:4200"
#    depends_on:
#      - app
#    networks:
#      - api_network

volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge